### ISSUE TITLE
[NIBR] Up and down genes are reversed in Metadata API

### ISSUE THREAD

**Issue by chienhsiang** [MaayanLab/signature-commons-ui#201]
Hi,

I think the up genes should be those with larger index in the ranked list and down genes should be those with smaller index, since genes are sorted in ascending manner during [rank conversion by SigCom controller](https://github.com/MaayanLab/signature-commons-controller/blob/fdacd14b9f884de7b3b05163cc15bb5c29d06685/controller/SignatureCommonsDataIngestion.java#L516) and [retrieval by SigCom UI](https://github.com/MaayanLab/signature-commons-ui/blob/4e22aabbbd39a999733ab0695f42cdab3b237dde/util/fetch/model.js#L419).
Therefore, [up_data](https://github.com/MaayanLab/signature-commons-ui/blob/4e22aabbbd39a999733ab0695f42cdab3b237dde/components/MetadataSearch/download.js#L215) should be `signature.data.slice((signature.data.length - 250))` and [down_data](https://github.com/MaayanLab/signature-commons-ui/blob/4e22aabbbd39a999733ab0695f42cdab3b237dde/components/MetadataSearch/download.js#L216) should be `signature.data.slice(0, 250)`. [Line 303](https://github.com/MaayanLab/signature-commons-ui/blob/4e22aabbbd39a999733ab0695f42cdab3b237dde/components/MetadataSearch/download.js#L303) and [line 310
](https://github.com/MaayanLab/signature-commons-ui/blob/4e22aabbbd39a999733ab0695f42cdab3b237dde/components/MetadataSearch/download.js#L310) should also be modified (and maybe other places?).

This explains why Z statistics of the Mann–Whitney U test have opposite signs when using drop-down menu of Metadata Search vs. direct Signature Search.

Please feel free to let me know if I misunderstand anything.

Many thanks,
Charles

**Comment by u8sand** [comment]
@chienhsiang Thanks for the report. We plan on working on this with several other data-api related things next week.

I'm wondering whether or not this is also the case for the enrichr libraries -- theses libraries were built differently prior to the development of the controller. If it is also, then we'll gladly apply this to the UI. Otherwise, we have to modify the data prior to doing it.

We're also looking into potentially using a slightly different scheme to make it more obvious in the future, i.e. negative ranks as down and positive ranks as up perhaps centered at 0.

**Comment by chienhsiang** [comment]
@u8sand,  I like the idea of using signed ranks. If there is anything I can help to test, please feel free to let me know.

**Comment by u8sand** [comment]
Confirmed in https://github.com/MaayanLab/signature-commons-controller/blob/3f57118e1d2e8495f7e6582998564140851e2777/controller/SignatureCommonsDataIngestion.java#L516

Instead of playing around with how we serialize it right now we're going to fix it as it is and potentially decide if we're going to use signed ranks later..
